services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: todo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todoapp

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=todoapp

  # Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongodb_data: