name: Simple CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    
    - name: Build and test services
      run: |
        docker-compose up --build -d
        sleep 30
        
        # Check backend health
        if curl -f http://localhost:5000/health; then
          echo "✅ Backend health check passed"
        else
          echo "❌ Backend health check failed"
          exit 1
        fi
        
        # Check backend API
        if curl -f http://localhost:5000/; then
          echo "✅ Backend API is working"
        else
          echo "❌ Backend API failed"
          exit 1
        fi
        
        docker-compose down
        echo "🎉 All tests passed!"